### PR TITLE
Extract method for collecting worker result

### PR DESCRIPTION
**Pull request by hanazuki**
I'm using test-queue with rspec in master-slave distributed mode over several machines. I would like to collect structured data such as test coverage metrics from the worker processes on both the master and the slave machines and summarize them on the master machine to calculate a coverage rate.

I've found that it would be handy to piggyback such miscellaneous data on the `WORKER` messages sent from the slaves to the master. But there is not an appropriate Runner method to override in order to prepare such an additional payload relayed from slaves.

This patch extracts routines related to a master collecting test results from a worker process as a method, in order to allow subclasses of Runner to collect application-specific data.

### CODE REVIEW

**Comment by hanazuki** [comment]
The following code illustrates my idea of calculating coverage rate in distributed running of tests.

`collect_worker_data` is a hook which runs for each worker after it finishes and before the worker result is relayed to the master machine.

```rb
module TestQueue
  class Worker
    attr_accessor :coverage  # additional payload
  end
end

class MyRSpecRunner < TestQueue::Runner::RSpec

  # this method runs at the end of every worker process
  def cleanup_worker
    store_coverage_for($$)
    super
  end

  # this method runs when a worker dies in the master process managing the worker
  def collect_worker_data(worker)
    worker.coverage = fetch_stored_coverage_for(worker.pid)
    super
  end

  # `worker` data will be relayed to the central master in distributed mode

  # this method runs in the central master process after all the workers have finished
  def summarize_worker(worker)
    merge_coverage(worker.coverage)
    super
  end

  # this method runs in the central master process
  def summarize
    calculate_coverage_rate
    super
  end
end
```

**Comment by hanazuki** [comment]
Rebased on the latest release. I have no idea why CI fails but it seems failing as the [latest master revision](https://travis-ci.org/tmm1/test-queue/builds/161703135)

Can you merge this change?  @aroben @bhuga

**Comment by aroben** [comment]
CI is passing now. This method makes sense to me. Thanks for adding it!

**Comment by hanazuki** [comment]
Thank you!

**Pull request merged**
