### PR TITLE
Support TEST_QUEUE_SPLIT_GROUPS for minitest5.

### PR DESCRIPTION
**Pull request by bboe**
Similar to #26 for minitest5.

This mode is enabled by setting the environment variable
`TEST_QUEUE_SPLIT_GROUPS`.

### CODE REVIEW

**Comment by tmm1** [comment]
Can you fix the merge conflicts in here?

**Comment by sbonebrake** [comment]
Why randomize the order when we have stats? Distributing the highest runtime tests first is a good greedy algorithm.

**Comment by bboe** [comment]
@tmm1 merge conflicts resoled.

@sbonebrake I didn't implement the sort by test time feature when splitting. At this granularity of splitting I feel like test time is less important than ensuring there is no dependency between tests. Such dependancies could result from tests always running in the same or similar order.

**Comment by bootstraponline** [comment]
I think test time is more important?

> The test runner keeps a persistent cache recording how long each test took on previous runs, and enqueues tests starting with the slowest. This ensures that slow tests start as soon as possible and is important for ensuring an optimal work distribution.
>
> https://stripe.com/blog/distributed-ruby-testing

**Comment by bhuga** [comment]
>  At this granularity of splitting I feel like test time is less important than ensuring there is no dependency between tests. Such dependancies could result from tests always running in the same or similar order.

The slowest-test-first handling is why test-queue parallelizes effectively. The `.shuffle` here would probably be considered a regression by some people already using this feature. I don't think we can land this while it randomizes test order.

Huge :+1: otherwise. I've implemented, badly, minitest5 per-example splitting for some experiments before.

**Comment by bboe** [comment]
Lots of great feedback. Thanks @bootstraponline and @bhuga.

> The .shuffle here would probably be considered a regression by some people already using this feature

This feature is opt-in thus it would not be a regression. Nevertheless, I agree that maintaining slowest-test first when splitting by test-case makes sense. I suppose I could make a separate PR to optionally run the tests in a random order. I'll work on maintaining the order soon.

**Comment by bboe** [comment]
@tmm1 @bhuga Test split by group are now ordered with longest tests first.

**Comment by bboe** [comment]
@tmm1 @bhuga ping

**Comment by bootstraponline** [comment]
> This branch has conflicts that must be resolved

**Comment by bboe** [comment]
I am no longer working on this project, so I've closed the PR.

**Pull request closed without merging**
