### PR TITLE
Set up a Travis CI build

### PR DESCRIPTION
**Pull request by aroben**
This branch replaces the `test.sh` and `test-multi.sh` scripts with automated tests run by Travis CI. Tests are written using https://github.com/sstephenson/bats, with helper functions in `test/testlib.bash`. We test each supported test framework in its own build.

These tests only slightly expand on the functionality of `test.sh` and `test-multi.sh`. We test that we exit successfully if all tests pass, and exit with failure if any tests fail, but that's about it. Still, I think this is an improvement because this is verified automatically against all test frameworks, and it's easy to add more detailed tests as we make further improvements to test-queue.

/cc @bhuga @tmm1

### CODE REVIEW

**Comment by aroben** [comment]
See the results at https://travis-ci.org/aroben/test-queue. @tmm1 will need to enable Travis for his fork for Travis info to show up in PRs.

**Comment by aroben** [comment]
I noticed that Cucumber 2.x is broken. I'll fix that separately and configure Travis to test it.

**Comment by tmm1** [comment]
Thanks, this has been sorely missing.

I enabled Travis CI for this repo.

**Comment by bhuga** [comment]
:metal: love it.

**Pull request merged**
